#!/bin/bash
#PBS -N Lippmann-Schwinger-inf-vol
#PBS -q red
#PBS -l walltime=48:00:00
#PBS -l cput=256:00:00
#PBS -l nodes=1:ppn=4
#PBS -j oe
#PBS -o /latticeQCD/raid6/darvish/eft-coupled-LS/cpp/iepsilon/jobs/E_700.log
#PBS -e /latticeQCD/raid6/darvish/eft-coupled-LS/cpp/iepsilon/jobs/E_700_err.log


export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export PATH=$PATH:/usr/local/bin

cd /latticeQCD/raid6/darvish/eft-coupled-LS/cpp/iepsilon/ && /latticeQCD/raid6/darvish/eft-coupled-LS/cpp/iepsilon/test-1b2c 700.000000
